apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: VSphereCluster
metadata:
  name: capi-demo
  namespace: default
spec:
  controlPlaneEndpoint:
    host: 10.201.25.100
    port: 6443
  identityRef:
    kind: Secret
    name: capi-demo
  server: 10.201.23.1
  thumbprint: ""
