apiVersion: addons.cluster.x-k8s.io/v1beta2
kind: ClusterResourceSet
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: capi-demo
  name: capi-demo-crs-0
  namespace: default
spec:
  clusterSelector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: capi-demo
  resources:
  - kind: Secret
    name: vsphere-config-secret
  - kind: ConfigMap
    name: csi-manifests
  - kind: Secret
    name: cloud-provider-vsphere-credentials
  - kind: ConfigMap
    name: cpi-manifests
